pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/backupnow/SQA_JAVA_PROGRAMMING.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('CuraHealth') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Publish Cucumber Report') {
            steps {
                dir('CuraHealth') {
                    publishHTML(target: [
                        reportDir: 'target/cucumber-reporting',
                        reportFiles: 'reports.html',
                        reportName: 'Cucumber Report',
                        keepAll: true,
                        alwaysLinkToLastBuild: true,
                        allowMissing: false
                    ])
                }
            }
        }
    }

    post {
        always {
            dir('CuraHealth') {
                archiveArtifacts artifacts: 'target/cucumber-reporting/**', fingerprint: true
            }
        }
    }
}
